### ISSUE TITLE
[FR] Update Metadata Dialogue View

### ISSUE THREAD

**Issue by seanwu1105** [numbersprotocol/starling-capture#16]
## Concept

If we make the metadata dialogue view more user friendly

![Starling Capture - UX Wireframes](https://user-images.githubusercontent.com/5687908/88823544-ca564480-d1f7-11ea-9d27-e0de7897df51.jpg)

## Reason/Hypothesis

We can help users understand what these metadata mean

## Todos

- [x] Show only high importance on the proof page.
- [x] Sort information by information type.
- [x] Show types with header and icon.

**Comment by seanwu1105** [comment]
Need to discuss how to define the "preview" of the information set.

**Comment by seanwu1105** [comment]
Add two attributes to the `Information` entity: group id and importance.

**Comment by seanwu1105** [comment]
![Screenshot_20200804-170046](https://user-images.githubusercontent.com/14951000/89275753-45df4800-d675-11ea-952f-37c6b1738cc3.png)

**Comment by scott-dt** [comment]
![Screenshot_20200810-141858](https://user-images.githubusercontent.com/62582260/89756252-8545e280-db14-11ea-8e67-deda50c11d18.png)
